version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "taskdef.json"
        LoadBalancerInfo:
          ContainerName: "my-app-container"
          ContainerPort: 80
