version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 152247411618.dkr.ecr.eu-west-1.amazonaws.com

      # Define repository URI
      - REPOSITORY_URI=152247411618.dkr.ecr.eu-west-1.amazonaws.com/kiran-my-app

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      # Build locally with name my-app:latest
      - docker build -t my-app:latest .
      # Tag local image to ECR repo (only latest)
      - docker tag my-app:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
      - echo Replacing placeholder in taskdef.json...
      - sed -i "s|IMAGE1_NAME|$REPOSITORY_URI:latest|" taskdef.json
      - echo Writing imagedefinitions.json file...
      - printf '[{"name":"my-app-container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:latest > imageDetail.json

artifacts:
  files:
    - 'image*.json'
    - 'appspec.yml'
    - 'taskdef.json'
  secondary-artifacts:
    BuildArtifact:
      files:
        - appspec.yml
        - taskdef.json
    ImageArtifact:
      files:
        - imagedefinitions.json
